### ISSUE TITLE
Настроить H2 DB на работу из нескольких сессий

### ISSUE THREAD

**Issue by turgeniev** [activity-time/activity#18]
Сейчас H2 позволяет работать только с одним коннектом, остальные падают с сообщением - файл заблокирован.

**Comment by turgeniev** [comment]
Не заработало.
Если запустить приложение, то одновременно зайти в БД из IDEA не получается - пишет ошибку - файл уже заблокирован

**Comment by andreevym** [comment]
нужно в IDEA изменить url: jdbc:h2:file:./db/activity-db;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
